package io.github.sanadlab.runtime;

import io.github.sanadlab.annotations.EvictionPolicy;
import io.github.sanadlab.annotations.ThreadSafety;

import java.util.concurrent.Callable;

/**
 * Per-method cache dispatcher. This is the core class called by ASM-generated
 * trampolines. Each memoized method gets its own MemoDispatcher instance.
 *
 * <p>The dispatcher manages cache lookup, computation on miss, and storage.
 * It handles null return values using a sentinel pattern.
 */
public final class MemoDispatcher {

    /** Sentinel value to distinguish "cached null" from "not cached". */
    private static final Object NULL_SENTINEL = new Object();

    private final MemoCache<CacheKeyWrapper, Object> cache;
    private final CacheStats stats;
    private final MemoMetrics metrics;
    private final String methodName;
    private final long expireAfterWriteMs;
    private final MemoCache<CacheKeyWrapper, Long> timestamps;

    // Auto-monitor state
    private final boolean autoMonitor;
    private final double minHitRate;
    private final int monitorWindow;
    private volatile boolean disabled;

    public MemoDispatcher(String methodName, int maxSize, long expireAfterWriteMs,
                          EvictionPolicy eviction, ThreadSafety threadSafety,
                          boolean recordStats, boolean autoMonitor,
                          double minHitRate, int monitorWindow) {
        this.methodName = methodName;
        this.expireAfterWriteMs = expireAfterWriteMs;
        this.autoMonitor = autoMonitor;
        this.minHitRate = minHitRate;
        this.monitorWindow = monitorWindow;
        this.disabled = false;

        // Auto-monitor requires stats tracking
        this.stats = (recordStats || autoMonitor) ? new CacheStats() : null;
        this.metrics = new MemoMetrics();

        this.cache = createCache(maxSize, eviction, threadSafety, this.stats);

        if (expireAfterWriteMs > 0) {
            this.timestamps = createCache(maxSize, EvictionPolicy.LRU, threadSafety, null);
        } else {
            this.timestamps = null;
        }

        if (MemoLogger.isLoggable(LogLevel.INFO)) {
            MemoLogger.info("dispatcher created method=" + methodName
                    + " maxSize=" + maxSize
                    + " ttlMs=" + expireAfterWriteMs
                    + " eviction=" + eviction
                    + " threadSafety=" + threadSafety
                    + " stats=" + (this.stats != null)
                    + " autoMonitor=" + autoMonitor);
        }
    }

    public MemoDispatcher(String methodName, int maxSize, long expireAfterWriteMs,
                          EvictionPolicy eviction, ThreadSafety threadSafety,
                          boolean recordStats) {
        this(methodName, maxSize, expireAfterWriteMs, eviction, threadSafety,
             recordStats, false, 0.3, 100);
    }

    /**
     * Simplified constructor with common defaults.
     */
    public MemoDispatcher(String methodName, int maxSize) {
        this(methodName, maxSize, -1, EvictionPolicy.LRU, ThreadSafety.CONCURRENT,
             false, false, 0.3, 100);
    }

    /**
     * Factory method called by ASM-generated bytecode. Takes string names for enums
     * to avoid complex enum GETSTATIC bytecode generation.
     */
    public static MemoDispatcher create(String methodName, int maxSize, long expireAfterWriteMs,
                                         String eviction, String threadSafety, boolean recordStats) {
        EvictionPolicy ep = EvictionPolicy.valueOf(eviction);
        ThreadSafety ts = ThreadSafety.valueOf(threadSafety);
        return new MemoDispatcher(methodName, maxSize, expireAfterWriteMs, ep, ts, recordStats);
    }

    /**
     * Full factory method with auto-monitor parameters.
     * Called by ASM when autoMonitor is enabled.
     */
    public static MemoDispatcher create(String methodName, int maxSize, long expireAfterWriteMs,
                                         String eviction, String threadSafety, boolean recordStats,
                                         boolean autoMonitor, double minHitRate, int monitorWindow) {
        EvictionPolicy ep = EvictionPolicy.valueOf(eviction);
        ThreadSafety ts = ThreadSafety.valueOf(threadSafety);
        return new MemoDispatcher(methodName, maxSize, expireAfterWriteMs, ep, ts,
                                  recordStats, autoMonitor, minHitRate, monitorWindow);
    }

    @SuppressWarnings("unchecked")
    private static <K, V> MemoCache<K, V> createCache(int maxSize, EvictionPolicy eviction,
                                                       ThreadSafety threadSafety, CacheStats stats) {
        switch (eviction) {
            case NONE:
                // Unbounded cache -- use ConcurrentHashMap regardless of threadSafety
                return new ConcurrentMemoCache<>();
            case FIFO:
                return new FifoMemoCache<>(maxSize, stats);
            case LFU:
                return new LfuMemoCache<>(maxSize, stats);
            case LRU:
            default:
                // LRU -- choose synchronized vs unsynchronized based on thread safety
                if (threadSafety == ThreadSafety.NONE) {
                    return new UnsynchronizedLruMemoCache<>(maxSize, stats);
                }
                return new LruMemoCache<>(maxSize, stats);
        }
    }

    /**
     * Check cache and compute on miss. Called by the ASM-generated trampoline.
     *
     * @param args    boxed method arguments
     * @param compute callable that invokes the original method
     * @return the (possibly cached) result
     */
    public Object invoke(Object[] args, Callable<Object> compute) throws Exception {
        // Logging is OFF by default; these locals cost nothing then.
        final boolean infoOn  = MemoLogger.isLoggable(LogLevel.INFO);
        final boolean debugOn = MemoLogger.isLoggable(LogLevel.DEBUG);
        final boolean traceOn = MemoLogger.isLoggable(LogLevel.TRACE);

        long lookupStart = infoOn ? System.nanoTime() : 0L;

        CacheKeyWrapper key = args.length == 0
                ? CacheKeyWrapper.EMPTY
                : new CacheKeyWrapper(args);

        // Check TTL expiry
        if (timestamps != null) {
            Long writeTime = timestamps.get(key);
            if (writeTime != null) {
                long elapsed = System.nanoTime() - writeTime;
                if (elapsed > expireAfterWriteMs * 1_000_000L) {
                    cache.remove(key);
                    timestamps.remove(key);
                    if (debugOn) {
                        MemoLogger.debug("ttl expired method=" + methodName
                                + " key=" + key.hashCode());
                    }
                }
            }
        }

        Object cached = cache.get(key);
        if (cached != null) {
            if (stats != null) stats.recordHit();
            if (infoOn) metrics.recordLookup(System.nanoTime() - lookupStart);
            if (traceOn) {
                MemoLogger.trace("hit method=" + methodName + " key=" + key.hashCode());
            }
            return cached == NULL_SENTINEL ? null : cached;
        }

        // Cache miss — compute
        if (stats != null) stats.recordMiss();
        if (debugOn) {
            MemoLogger.debug("miss method=" + methodName + " key=" + key.hashCode());
        }

        long computeStart = infoOn ? System.nanoTime() : 0L;
        Object result;
        try {
            result = compute.call();
        } catch (Exception ex) {
            if (MemoLogger.isLoggable(LogLevel.ERROR)) {
                MemoLogger.error("compute threw method=" + methodName, ex);
            }
            throw ex;
        }
        if (infoOn) metrics.recordCompute(System.nanoTime() - computeStart);

        Object toStore = result != null ? result : NULL_SENTINEL;
        cache.put(key, toStore);

        if (timestamps != null) {
            timestamps.put(key, System.nanoTime());
        }

        return result;
    }

    /**
     * Evict a single cached entry identified by its argument tuple. No-op if
     * the entry is absent. Used by {@code @InvalidateCacheEntry}-generated
     * bytecode to drop one stale row without wiping the whole cache.
     */
    public void invalidateEntry(Object[] args) {
        CacheKeyWrapper key = args.length == 0 ? CacheKeyWrapper.EMPTY : new CacheKeyWrapper(args);
        invalidateEntry(key);
    }

    /**
     * Variant for call sites that already built a {@link CacheKeyWrapper}.
     */
    public void invalidateEntry(CacheKeyWrapper key) {
        cache.remove(key);
        if (timestamps != null) {
            timestamps.remove(key);
        }
        if (MemoLogger.isLoggable(LogLevel.DEBUG)) {
            MemoLogger.debug("invalidateEntry method=" + methodName
                    + " key=" + key.hashCode());
        }
    }

    /**
     * Clear all cached entries for this method.
     */
    public void invalidate() {
        if (MemoLogger.isLoggable(LogLevel.INFO)) {
            MemoLogger.info("invalidate method=" + methodName + " size=" + cache.size());
        }
        cache.clear();
        if (timestamps != null) {
            timestamps.clear();
        }
    }

    public String getMethodName() {
        return methodName;
    }

    public CacheStats getStats() {
        return stats;
    }

    public MemoMetrics getMetrics() {
        return metrics;
    }

    public int size() {
        return cache.size();
    }

    /**
     * Whether auto-monitor has disabled this cache due to low hit rate.
     */
    public boolean isDisabled() {
        return disabled;
    }

    /**
     * Re-enable the cache after auto-monitor disabled it.
     * Resets stats so the monitor window starts fresh.
     */
    public void reenable() {
        disabled = false;
        if (stats != null) stats.reset();
    }

    // --- Methods used by ASM-injected bytecode (inline cache pattern) ---

    /**
     * Build a cache key from boxed method arguments.
     * Called by ASM-injected code at method entry.
     */
    public CacheKeyWrapper buildKey(Object[] args) {
        return args.length == 0 ? CacheKeyWrapper.EMPTY : new CacheKeyWrapper(args);
    }

    /**
     * Check the cache for a hit. Returns the cached value, NULL_SENTINEL for cached nulls,
     * or null for a cache miss.
     * Called by ASM-injected code at method entry.
     *
     * When auto-monitor is active and the cache has been disabled, always returns null
     * (cache bypass) so the original method body executes every time.
     */
    public Object getIfCached(CacheKeyWrapper key) {
        final boolean infoOn  = MemoLogger.isLoggable(LogLevel.INFO);
        final boolean debugOn = MemoLogger.isLoggable(LogLevel.DEBUG);
        final boolean traceOn = MemoLogger.isLoggable(LogLevel.TRACE);
        long lookupStart = infoOn ? System.nanoTime() : 0L;

        // If auto-monitor disabled the cache, bypass entirely
        if (disabled) {
            if (traceOn) MemoLogger.trace("bypass (disabled) method=" + methodName);
            return null;
        }

        // Check TTL expiry
        if (timestamps != null) {
            Long writeTime = timestamps.get(key);
            if (writeTime != null) {
                long elapsed = System.nanoTime() - writeTime;
                if (elapsed > expireAfterWriteMs * 1_000_000L) {
                    cache.remove(key);
                    timestamps.remove(key);
                    if (stats != null) stats.recordMiss();
                    if (debugOn) {
                        MemoLogger.debug("ttl expired method=" + methodName
                                + " key=" + key.hashCode());
                    }
                    return null;
                }
            }
        }

        Object cached = cache.get(key);
        if (cached != null) {
            if (stats != null) stats.recordHit();
            if (infoOn) metrics.recordLookup(System.nanoTime() - lookupStart);
            if (traceOn) {
                MemoLogger.trace("hit method=" + methodName + " key=" + key.hashCode());
            }
            return cached;
        }
        if (stats != null) stats.recordMiss();
        if (debugOn) {
            MemoLogger.debug("miss method=" + methodName + " key=" + key.hashCode());
        }
        return null;
    }

    /**
     * Start time of a compute, for the compute metrics. Called by ASM-injected
     * code on a cache miss. Returns {@code System.nanoTime()} when INFO logging
     * is on, else 0. With logging off, the cost is one volatile read.
     */
    public long computeStart() {
        return MemoLogger.isLoggable(LogLevel.INFO) ? System.nanoTime() : 0L;
    }

    /**
     * Same as {@link #putInCache(CacheKeyWrapper, Object)}, and records the
     * compute time when {@code computeStart} is not 0.
     * Called by ASM-injected code before method return.
     */
    public Object putInCache(CacheKeyWrapper key, Object result, long computeStart) {
        if (computeStart != 0L) metrics.recordCompute(System.nanoTime() - computeStart);
        return putInCache(key, result);
    }

    /**
     * Store a computed result in the cache.
     * Kept for classes transformed by older plugin versions.
     *
     * When auto-monitor is active, this also evaluates whether to disable
     * the cache after the monitor window is reached.
     *
     * @return the original (unwrapped) result for convenience
     */
    public Object putInCache(CacheKeyWrapper key, Object result) {
        // If auto-monitor disabled the cache, don't store
        if (disabled) {
            return result;
        }

        Object toStore = result != null ? result : NULL_SENTINEL;
        cache.put(key, toStore);
        if (timestamps != null) {
            timestamps.put(key, System.nanoTime());
        }

        // Auto-monitor: check if we should disable caching
        if (autoMonitor && stats != null) {
            long totalRequests = stats.getRequestCount();
            if (totalRequests >= monitorWindow) {
                double hitRate = stats.getHitRate();
                if (hitRate < minHitRate) {
                    disabled = true;
                    cache.clear(); // Free memory since cache is no longer useful
                    if (timestamps != null) timestamps.clear();
                    if (MemoLogger.isLoggable(LogLevel.WARN)) {
                        MemoLogger.warn(String.format(
                                "auto-monitor disabled cache method=%s hitRate=%.2f requests=%d",
                                methodName, hitRate, totalRequests));
                    }
                }
            }
        }

        return result;
    }

    /**
     * Unwrap a cached value (converts NULL_SENTINEL back to null).
     */
    public static Object unwrap(Object cached) {
        return cached == NULL_SENTINEL ? null : cached;
    }

    /**
     * Check if a cached value represents a cached null.
     */
    public static boolean isNullSentinel(Object cached) {
        return cached == NULL_SENTINEL;
    }
}
